- name: catalogue setup
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create ansible roboshop user
    ansible.builtin.user:
      name: roboshop
      comment: robosgop user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create app directory
    ansible.builtin.file:
     state: directory
     path: /app

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: unzip /tmp/catalogue.zip

  - name: unzipping catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      
