- name:  configure frontend server  
  hosts: frontend
  become: yes
  tasks:
  - name: Disable default nginix
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf: 
      name: nginx
      state: present

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html 
      state: abesent

  - name: crate html directory
    ansible.builtin.file:
      state: directory
      path: /usr/share/nginx/html

  - name: download frontend application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzipping frontend
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: delete default nginx configuration
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy nginx conf
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.service: 
     name: nginx
     state: restarted
     enable: yes