- name: user setup
  hosts: user
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create ansible roboshop user
    ansible.builtin.user:
      name: roboshop
      comment: robosgop user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create app directory
    ansible.builtin.file:
     state: directory
     path: /app

  - name: Delete catalogue file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: download user application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: unzipping user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app  

  - name: copy user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service


  # - name: evaluate user database
  #   community.mongodb.mongodb_shell:
  #     login_host: mongodb.practicedev.shop
  #     eval: db.getMongo().getDBNames().indexOf('user')
  #   register: user_output

  # - name: print user output
  #   ansible.builtin.debug:
  #     msg: "{{ user_output }}"


  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: user
      enabled: true
      state: started
      daemon_reload: true



